---
title: "NIH EXPORTER"
author: "Jay Hesselberth"
date: "3/7/2015"
output: html_document
---

```{r, message=FALSE}
library(dplyr)
library(ggplot2)
library(knitr)
library(nihexporter)
```

```{r}
projects %>%
  group_by(fiscal.year, institute) %>%
  summarize(yearly.cost = sum(total.cost, na.rm = TRUE)) %>%
  filter(yearly.cost > 0) %>%
  arrange(yearly.cost) %>%
  ggplot(aes(x = fiscal.year, y = yearly.cost)) +
  geom_line() +
  facet_wrap(~ institute)
```

```{r biggest.losers}
projects %>%
  filter(total.cost > 0 & activity == 'R01') %>%
  group_by(project.num) %>%
  summarise(overall.cost = sum(total.cost)) %>%
  left_join(publinks) %>%
  filter(!is.na(pmid)) %>%
  group_by(project.num, overall.cost) %>%
  summarize(n.pubs = n()) %>%
  mutate(cost.per.pub = overall.cost / n.pubs) %>%
  ungroup() %>%
  arrange(desc(cost.per.pub)) %>%
  head(50) %>%
  kable()
```

```{r}
projects %>%
  group_by(fiscal.year, institute) %>%
  summarize(yearly.cost = sum(total.cost)) %>%
  head()
```

```{r spending.over.time}
projects %>%
  group_by(institute, activity, fiscal.year) %>%
  summarize(total = sum(total.cost, na.rm = TRUE)) %>%
  filter(total > 0) %>%
  ggplot(aes(x = fiscal.year, y = total, color = institute)) +
  geom_line() +
  facet_wrap(~ activity) +
  scale_y_log10()
```

