---
title: "`nihexporter` interactive analysis"
author: "Jay Hesselberth"
date: "Last update: `r format(Sys.time(), '%d %B, %Y')`"
output: html_document
runtime: shiny
---

```{r load.libs, echo = FALSE, message = FALSE, warning = FALSE}
library(dplyr)
library(scales)
library(ggplot2)
library(lubridate)
library(nihexporter)
```

# Overview

These interactive plots support the manuscript describing the [`nihexporter` R data package](https://github.com/jayhesselberth/nihexporter).

# Funding trends

This interactive plot shows total grant costs for selected activities (i.e., grant types) in specific [NIH institutes](http://grants.nih.gov/grants/acronym_list.htm).

```{r funding_trends, echo=FALSE}
grant_types <- projects %>%
  select(activity) %>%
  distinct() %>%
  sapply(as.character) %>% as.vector

min_fiscal_year <- as.integer(min(projects$fiscal.year))
max_fiscal_year <- as.integer(max(projects$fiscal.year))

inputPanel(
  selectInput("nih_institutes", label = "Institute:",
              choices = nih.institutes, selected = c('GM','CA','AI'), 
              multiple = TRUE),
  selectInput("activities", label = "Activity:",
              choices = grant_types, selected = c('R01','P01'),
              multiple = TRUE),
  sliderInput("fiscal_years", label = "Fiscal years:",
              min = min_fiscal_year,
              max = max_fiscal_year,
              value = c(2010, 2014),
              sep = "",
              step = 1)
)

renderPlot({
  
  inst_costs <- projects %>%
    filter(institute %in% input$nih_institutes &
           activity %in% input$activities &
           fiscal.year >= input$fiscal_years[1] &
           fiscal.year <= input$fiscal_years[2]) %>%
    select(project.num, institute, activity, fiscal.year, total.cost) %>%
    group_by(project.num, activity, institute, fiscal.year) %>%
    summarize(grant.cost = sum(total.cost, na.rm = TRUE))
  
  ggplot(inst_costs, aes(x = factor(fiscal.year),
                         y = grant.cost, 
                         fill = activity)) +
    geom_boxplot(outlier.size = 0.2) + 
    facet_wrap(~ institute) + 
    scale_y_log10(limits = c(9e4, 1e7),
                  labels = trans_format("log10", math_format(10^.x))) + 
    annotation_logticks(sides = "l",
                        scaled = TRUE) +
    scale_fill_brewer(palette="Dark2") +
    xlab('') +
    ylab('Total grant dollars, log-scaled') +
    theme_bw() +
    theme(axis.text.x = element_text(angle = 90),
          legend.position = 'bottom')
  
})
```

# Productivity

This interactive plot compares the number of publications to the total (indirect + direct) dollar cost of grants.

```{r productivity, echo = FALSE, warning = FALSE, message = FALSE}

grant_pubs <- projects %>%
  select(project.num) %>%
  distinct() %>%
  left_join(publinks) %>%
  group_by(project.num) %>%
  summarise(n.pubs = n())
 
inputPanel(
  selectInput("nih_institutes", label = "Institute:",
              choices = nih.institutes, selected = c('GM','CA','AI'), 
              multiple = TRUE),
  selectInput("activity", label = "Activity:",
              choices = grant_types, selected = c('R01'))
)

renderPlot({
  
  # calculate costs of all grants, over the entire lifetime of the grant
  select_grant_costs <- projects %>%
    filter(institute %in% input$nih_institutes &
           activity == input$activity) %>%
    select(project.num, activity, institute, total.cost) %>%
    group_by(project.num, activity, institute) %>%
    summarise(grant.cost = sum(total.cost, na.rm = TRUE))
 
  min.grant.cost <- round(min(select_grant_costs$grant.cost), -4) # round to 10,000s
  max.grant.cost <- round(max(select_grant_costs$grant.cost), -5) 
  # step is average size of an award
  if (max.grant.cost < 1e6) {
    step <- 1e5
  } else {
    step <- 1e6
  }

  breaks <- seq(min.grant.cost, max.grant.cost, step)

  bin_grant_costs <- select_grant_costs %>%
    group_by(institute) %>%
    mutate(dollar.tile = findInterval(grant.cost, vec = breaks, 
                                      all.inside = TRUE, rightmost.closed = TRUE))

  productivity <- bin_grant_costs %>%
    left_join(grant_pubs)

  ggplot(productivity, aes(x = factor(dollar.tile),
                           y = n.pubs)) +
    geom_boxplot(outlier.shape = NA) +
    scale_x_discrete(labels = round(breaks / 1e6, 0)) + 
    scale_y_log10() +
    facet_wrap(~ institute, scales = "free_x") +
    ylab('Number of publications') +
    xlab('Total costs (minimum, in millions)') +
    theme_bw()
})
```




