---
title: <center> Final Project
author: <center> Nick Ellinwood
date: <center> May 5, 2015
output: html_document
---


#Goal: Let's make NIH funding data accessible!

## Load Packages:
```{r, Packages, echo=TRUE, cache=TRUE}
library(nihexporter)
library(dplyr)
library(ggplot2)
library(knitr)
```

```{r, Code, echo=TRUE, cache=TRUE}
library(nihexporter)
library(dplyr)
library(ggplot2)

names(projects)

```

```{r, cache=TRUE, echo=TRUE}

#Regular Standing Study Sections

study.section <- c('ACE', 'ACTS', 'ADDT', 'AICS', 'AIP', 'AMCB', 'ANIE', 'AOIC', 'APDA', 'ASG', 'AUD', 'BACP', 'BBM', 'BCHI', 'BDMA', 'BGES', 'BINP', 'BMBI', 'BMCT', 'BMIO', 'BMITA', 'BMITB', 'BMRD', 'BNVT', 'BPNS', 'BRLE', 'BSCH', 'BSPH', 'BTSS', 'BVS', 'CADO', 'CAMP', 'CASE', 'CBSS', 'CCHF', 'CDD', 'CDIN', 'CDP', 'CE', 'CG', 'CICS', 'CIDO', 'CIHB', 'CII', 'CIMG', 'CLHP', 'CMAD', 'CMBG', 'CMIA', 'CMIB', 'CMIP', 'CMIR', 'CMND', 'CNBT', 'CNN', 'CNNT', 'CONC', 'CP', 'CPDD', 'CRFS', 'CSRS', 'DBD', 'DDNS', 'DDR', 'DEV1', 'DEV2', 'DIRH', 'DMP', 'DPVS', 'DT', 'EBIT', 'EPIC', 'ESTA', 'GCAT', 'GDD', 'GHD', 'GMPB', 'GVE', 'HAI', 'HBPP', 'HDEP', 'HIBP', 'HM', 'HSOD', 'HT', 'ICER', 'ICI', 'ICP1', 'IHD', 'III', 'INMP', 'IPOD', 'IRAP', 'ISD', 'KMBD', 'KNOD', 'LAM', 'LCMI', 'LCOM', 'LIRR', 'MABS', 'MBPP', 'MCE', 'MCH', 'MEDI', 'MESH', 'MFSR', 'MGA', 'MGB', 'MIM', 'MIST', 'MNG', 'MNPS', 'MONC', 'MRS', 'MSFA', 'MSFB', 'MSFC', 'MSFD', 'MSFD-N', 'MSFE', 'MTE', 'NAED', 'NAL', 'NAME', 'NANO', 'NCF', 'NCSD', 'NDPR', 'NMB', 'NNRS', 'NOIT', 'NOMD', 'NPAS', 'NRCS', 'NTRC', 'ODCS', 'PBKD', 'PCMB', 'PDRP', 'PMDA', 'PN', 'PRDP', 'PTHE', 'RIBT', 'RPIA', 'RTB', 'SAT', 'SBCA', 'SBCB', 'SBDD', 'SBSR', 'SCS', 'SEIR', 'SIEE', 'SIEE-C', 'SMEP', 'SMI', 'SPC', 'SPIP', 'SSPA', 'SSPB', 'SYN', 'TAG', 'TAG-Q', 'TCB', 'TME', 'TPM', 'TTT', 'UGPP', 'VACC', 'VB', 'VCMB', 'VIRA', 'VIRB', 'VMD', 'XNDA')

subj_area <- c('medicine', 'medicine', 'medicine', 'medicine', 'medicine', 'medicine', 'medicine', 'medicine', 'medicine', 'life_science', 'life_science', 'life_science', 'life_science', 'bio_methods', 'bio_methods', 'life_science', 'medicine', 'life_science', 'medicine', 'medicine', 'medicine', 'medicine', 'bio_methods', 'bioengineering', 'life_science', 'soc_beh', 'soc_beh', 'soc_beh', 'bioengineering', 'life_science', 'medicine', 'medicine', 'pop_health', 'medicine', 'life_science', 'life_science', 'medicine', 'pop_health', 'medicine', 'medicine', 'medicine', 'medicine', 'pop_health', 'medicine', 'medicine', 'pop_health', 'life_science', 'life_science', 'life_science', 'life_science', 'medicine', 'life_science', 'life_science', 'medicine', 'medicine', 'medicine', 'medicine', 'life_science', 'medicine', 'medicine', 'life_science', 'medicine', 'medicine', 'medicine', 'life_science', 'life_science', 'pop_health', 'medicine', 'medicine', 'medicine', 'bio_methods', 'pop_health', 'life_science', 'bio_methods', 'medicine', 'medicine', 'medicine', 'life_science', 'medicine', 'medicine', 'pop_health', 'medicine', 'medicine', 'pop_health', 'life_science', 'medicine', 'life_science', 'pop_health', 'life_science', 'life_science', 'life_science', 'medicine', 'medicine', 'bio_methods', 'life_science', 'medicine', 'life_science', 'life_science', 'soc_beh', 'medicine', 'bio_methods', 'life_science', 'life_science', 'life_science', 'bio_methods', 'soc_beh', 'medicine', 'life_science', 'life_science', 'life_science', 'life_science', 'life_science', 'medicine', 'medicine', 'life_science', 'life_science', 'life_science', 'life_science', 'life_science', 'life_science', 'life_science', 'bioengineering', 'medicine', 'life_science', 'pop_health', 'bioengineering', 'life_science', 'life_science', 'life_science', 'life_science', 'life_science', 'bio_methods', 'life_science', 'medicine', 'medicine', 'life_science', 'medicine', 'medicine', 'life_science', 'soc_beh', 'medicine', 'medicine', 'soc_beh', 'life_science', 'life_science', 'pop_health', 'medicine', 'medicine', 'bioengineering', 'bioengineering', 'life_science', 'life_science', 'life_science', 'soc_beh', 'pop_health', 'pop_health', 'life_science', 'life_science', 'life_science', 'soc_beh', 'soc_beh', 'pop_health', 'life_science', 'medicine', 'medicine', 'life_science', 'life_science', 'medicine', 'medicine', 'life_science', 'medicine', 'life_science', 'life_science', 'medicine', 'medicine', 'medicine', 'medicine')  
  
project.areas <- data.frame(study.section, subj_area)
project.areas <- tbl_df(project.areas)

# n for each specific group
n.project.areas <- project.areas %>%
  group_by(subj_area) %>%
  count(subj_area)
n.project.areas

# only analyze the projects dataset that contain a standing study section 
ss <- inner_join(projects, project.areas)

# n for each group in the ss dataset
n.ss <- ss %>%
  group_by(subj_area) %>%
  count(subj_area)
n.ss



#####################################################
#####################################################
################   RO1         ######################
#####################################################
#####################################################

#project number cost by suffix (R01) and study section
grant_costs_by_section <- ss %>%
  filter(activity == 'R01') %>%
  select(project.num, subj_area, total.cost) %>%
  group_by(project.num, subj_area) %>%
  summarize(grant.cost = sum(total.cost))
grant_costs_by_section


#productivity by project number and section
grant_productivity <- grant_costs_by_section %>%
  left_join(publinks) %>%
  group_by(project.num, subj_area, grant.cost) %>%
  summarize(n.pubs = n()) %>%
  mutate(cost.per.pub = grant.cost/n.pubs)
grant_productivity

# total publication per subj_area
pubnumber <- grant_productivity %>%
  group_by(subj_area) %>%
  summarize(sum(n.pubs))
pubnumber


# there are just a couple of NAs in the dataset 
here <- na.omit(grant_productivity)

# largest = $12 million
# smallest two = three cents and 1 dollar
#mean cost per pub
mean.pub <- here %>%
  group_by(subj_area) %>%
  summarize(mean(cost.per.pub))
mean.pub

#####################################################
#####################################################
##########   Don't filter activity         ##########
#####################################################
#####################################################


#project number cost by suffix (No filter on activity) and study section
grant_costs_by_section2 <- ss %>%
  select(project.num, subj_area, total.cost) %>%
  group_by(project.num, subj_area) %>%
  summarize(grant.cost = sum(total.cost))
grant_costs_by_section2

#productivity by project number and section
grant_productivity2 <- grant_costs_by_section2 %>%
  left_join(publinks) %>%
  group_by(project.num, subj_area, grant.cost) %>%
  summarize(n.pubs = n()) %>%
  mutate(cost.per.pub = grant.cost/n.pubs)
grant_productivity2

# total publication per subj_area
pubnumber2 <- grant_productivity2 %>%
  group_by(subj_area) %>%
  summarize(sum(n.pubs))
pubnumber2

# there are just a couple of NAs in the dataset 
here2 <- na.omit(grant_productivity2)

# largest = $12 million
# smallest two = three cents and 1 dollar

#mean cost per pub
mean.pub2 <- here2 %>%
  group_by(subj_area) %>%
  summarize(mean(cost.per.pub))
mean.pub2


#####################################################
#####################################################
################   ggplot2      #####################
#####################################################
#####################################################


ggplot(here2, aes(x = subj_area, y = cost.per.pub)) +
  geom_boxplot() +
  ggtitle('Cos Per Publication Boxplot')

public <- here2 %>%
  filter(subj_area == "pop_health")

# skewed, but one-way anovas are robust
hist(public$cost.per.pub)

#####################################################
#####################################################
################   STATS R01     ##############
#####################################################
#####################################################


boxesR01 <- boxplot(here$cost.per.pub ~ here$subj_area)

aov.subjR01 <- aov(here$cost.per.pub ~ here$subj_area)
summary(aov.subjR01)

posthocR01 <- TukeyHSD(aov.subjR01)
posthocR01

kruskal <- kruskal.test(cost.per.pub ~ subj_area, data = here)
kruskal

#####################################################
#####################################################
################   STATS No Filter     ##############
#####################################################
#####################################################

boxes <- boxplot(here2$cost.per.pub ~ here2$subj_area)

aov.subj <- aov(here2$cost.per.pub ~ here2$subj_area)
summary(aov.subj)

posthoc <- TukeyHSD(aov.subj)
posthoc

kruskal2 <- kruskal.test(cost.per.pub ~ subj_area, data = here2)
kruskal2

#####################################################
#####################################################
################# Patents     #######################
#####################################################
#####################################################

#project number cost by suffix (No filter on activity) and study section
cost.by.area <- ss %>%
  select(project.num, subj_area, total.cost) %>%
  group_by(project.num, subj_area) %>%
  summarize(grant.cost = sum(total.cost))
cost.by.area

#productivity by project number and section
productivity <- cost.by.area %>%
  left_join(patents) %>%
  group_by(project.num, subj_area, grant.cost)

here3 <- na.omit(productivity)

productivity2 <- here3 %>%
  group_by(project.num, subj_area, grant.cost) %>%
  summarize(n.pat = n()) %>%
  mutate(cost.per.pat = grant.cost/n.pat)
productivity2

# total patents per subj_area
patnumber <- productivity2 %>%
  group_by(subj_area) %>%
  summarize(sum(n.pat))
patnumber

#mean cost per pub
mean.pub2 <- productivity2 %>%
  group_by(subj_area) %>%
  summarize(mean(cost.per.pat))
mean.pub2

#####################################################
#####################################################
################   ggplot2 Patents     ##############
#####################################################
#####################################################


ggplot(productivity2, aes(x = subj_area, y = cost.per.pat)) +
  geom_boxplot() +
  ggtitle('Cost Per Patent')

#####################################################
#####################################################
################   STATS For Patents    #############
#####################################################
#####################################################


aov.pat <- aov(productivity2$cost.per.pat ~ productivity2$subj_area)
summary(aov.pat)

# only public health and bioengineery signficantly differ
posthoc.pat <- TukeyHSD(aov.pat)
posthoc.pat

kruskal.pat <- kruskal.test(cost.per.pat ~ subj_area, data = productivity2)
kruskal.pat

# one public health paper has 10 patents (R01CA049837)
# PUBLIC HEALTH RELEVANCE: Despite recent advances, breast cancer-associated morbidity and mortality remains a serious problem in the USA. The analogs of 4-HPR we are developing, show real promise as more effective and less toxic preventive and therapeutic agents for breast cancer. A clearer understanding of how these promising molecules function would further enhance our ability to develop and exploit them.

# they are referring to a synthetic compound

pub.health.pat <- productivity2 %>%
  filter(subj_area == "pop_health")
pub.health.pat

```



## Session Info:
```{r SessionInfo, echo=T, cache=T}
sessionInfo()
```

