---
title: "sentiment-analysis"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{sentiment-analysis}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r}
#| label: "knitr-opts"
#| include: false
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

```{r}
#| label: "setup"
#| message: false
library(nihexporter)
library(tidyverse)
library(tidymodels)
library(textrecipes)
```

## Sentiment analysis across time and institute

```{r}
#| label: "prep-training"
#| warning: false
set.seed(123)

select_institutes <- c("AI", "CA", "HL", "GM")
select_activities <- c("R01", "R21")

abstract_data <-
  filter(
    abstract_words,
    institute %in% select_institutes,
    activity %in% select_activities
  )

abstract_split <- initial_split(abstract_data, strata = institute)
abstract_train <- training(abstract_split)
abstract_test <- testing(abstract_split)

abstract_rec <- recipe(activity + fiscal_year ~ word, data = abstract_train) |>
  step_tokenize(word) |>
  step_stopwords(word) |>
  step_tokenfilter(word, max_tokens = 1000) |>
  step_tfidf(word) |>
  step_normalize(all_predictors())

abstract_prep <- prep(abstract_rec)

abstract_prep
```

```{r}
#| label: "prepare-engine-data"
#| warning: false
lasso_spec <- logistic_reg(penalty = tune(), mixture = 1) |>
  set_engine("glmnet")

lasso_wf <- workflow() |>
  add_recipe(abstract_rec) |>
  add_model(lasso_spec)

lambda_grid <- grid_regular(penalty(), levels = 40)

set.seed(123)
abstract_folds <- bootstraps(abstract_train, strata = institute)
abstract_folds
```

```{r}
#| label: "train-model"
#| warning: false
doParallel::registerDoParallel()

set.seed(1875)
lasso_grid <- tune_grid(
  lasso_wf,
  resamples = abstract_folds,
  grid = lambda_grid,
  metrics = metric_set(roc_auc, ppv, npv)
)

```
## Inspiration

- https://juliasilge.com/blog/animal-crossing/
- https://textrecipes.tidymodels.org/articles/cookbook---using-more-complex-recipes-involving-text.html
